[workspace]
authors = ["fkt <deepthought@postech.ac.kr>"]
channels = ["conda-forge"]
name = "quarto-book-template"
platforms = ["osx-arm64", "linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
quarto = ">=1.8.27,<2"
python = ">=3.14.3,<3.15"

[pypi-dependencies]
pymupdf = ">=1.26.7, <2"
ebooklib = ">=0.20, <0.21"
beautifulsoup4 = ">=4.14.3, <5"
pyyaml = ">=6.0.3, <7"
html2text = ">=2025.4.15, <2026"
